### ISSUE TITLE
Travis continuous integration notifications

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#83]
Leaving this here in case we want to enable notifications at some point. 

```yml
notifications:
  email:
    recipients:
      - email@email.com
```
